export const pricingPlans = [
  {
    title: "Freelancer",
    price: 24,
    currency: "PGK",
    frequency: "/month",
    description: "The essentials to provide your best work clients.",
    features: [
      "5 products",
      "Up to 1,000 subscribers",
      "Basic analytics",
      "48-hour support response time",
    ],
    cta: "Start your trial",
    mostPopular: false,
  },
  {
    title: "Startup",
    price: 32,
    currency: "PGK",
    frequency: "/month",
    description: "A plan that scales with your rapidly graowing business.",
    features: [
      "25 products",
      "Up to 10, 000 subscribers",
      "Advanced analytics",
      "24-hour support response time",
      "Marketing automations",
    ],
    cta: "Start your trial",
    mostPopular: true,
  },
  {
    title: "Enterprise",
    price: 48,
    currency: "PGK",
    frequency: "/month",
    description: "Dedicated support and infrastructure for your company.",
    features: [
      "Unlimited products",
      "Unlimited subscribers",
      "Advanced analytics",
      "One-hour, dedicated support response time",
      "Marketing automations",
      "Salesforce, Clearbit Reveal & Marketo integrations",
    ],
    cta: "Start your trial",
    mostPopular: false,
  },
];
