import Head from "next/head";
import Image from "next/image";
import PricingPlans from "../components/PricingPlans";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-7xl bg-white px-4 pt-24 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-extrabold text-gray-700 sm:text-5xl sm:leading-tight sm:tracking-tight">
          Pricing plans for teams of all sizes.
        </h2>
        <p className="mt-4 max-w-3xl text-lg text-slate-500">
          Choose an affordable plan that's packed with the best features for
          engaging your audience, creating customer loyalty and driving sales.
        </p>
      </div>
      <PricingPlans />
    </div>
  );
}
